# Generated by Django 5.0.7 on 2024-08-16 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('client', 'Client')], max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles', to='users.role'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.ManyToManyField(related_name='staff_profiles', to='users.role'),
        ),
    ]
