# Generated by Django 5.0.7 on 2024-10-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_realated_name_of_profile_class_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(related_name='profiles', to='users.role'),
        ),
    ]
