# Generated by Django 5.0.7 on 2024-08-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='approachfeature',
            table='ApproachFeature',
        ),
        migrations.AlterModelTable(
            name='missionapproach',
            table='MissionApproach',
        ),
        migrations.AlterModelTable(
            name='missionimage',
            table='MissionImage',
        ),
        migrations.AlterModelTable(
            name='missionvideo',
            table='MissionVideo',
        ),
        migrations.AlterModelTable(
            name='service',
            table='Service',
        ),
        migrations.AlterModelTable(
            name='servicemission',
            table='ServiceMission',
        ),
    ]
