# Generated by Django 5.0.7 on 2024-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_db_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionapproach',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
