# Generated by Django 5.0.7 on 2024-10-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_missionapproach_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionApproach',
            new_name='Approach',
        ),
        migrations.RenameModel(
            old_name='ApproachFeature',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='ServiceMission',
            new_name='Mission',
        ),
        migrations.AlterModelTable(
            name='approach',
            table='Approach',
        ),
        migrations.AlterModelTable(
            name='feature',
            table='Feature',
        ),
        migrations.AlterModelTable(
            name='mission',
            table='Mission',
        ),
    ]
