# Generated by Django 5.0.7 on 2024-08-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_create_intial_tables_to_community_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
