# Generated by Django 5.0.7 on 2024-09-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('descriptive_name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ComponentType',
            },
        ),
        migrations.CreateModel(
            name='RobotType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=400, unique=True)),
                ('descriptive_name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'RobotType',
            },
        ),
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('descriptive_name', models.CharField(blank=True, max_length=400, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.componenttype')),
            ],
            options={
                'db_table': 'ComponentModel',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('version', models.CharField(max_length=200, unique=True)),
                ('descriptive_name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_maintenance', 'In Maintenance'), ('deployed', 'Deployed'), ('decommissioned', 'Decommissioned'), ('reserved', 'Reserved')], default='available', max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='robots/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='robots/videos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('robot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='products.robottype')),
            ],
            options={
                'db_table': 'Robot',
            },
        ),
        migrations.CreateModel(
            name='RobotComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('component_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_components', to='products.componentmodel')),
                ('robot_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.robot')),
            ],
            options={
                'db_table': 'RobotComponent',
                'unique_together': {('robot_model', 'component_model')},
            },
        ),
    ]
